### ISSUE TITLE
Crash after opening tab list for some tab list configurations for some servers

### ISSUE THREAD

**Issue by Purrrpley** [hibiii/Kappa#4]
A server I play on recently changed their tab list again due to unrelated issues, but this time whenever I tried to view it it would render a few frames and then crash. I wanted to figure out which mod was causing it without spamming join messages there so tried to set up a test server on my own computer with a similar tab list (using same plugins and stuff, which is a [PaperMC](https://github.com/PaperMC/Paper) server running behind [BungeeCord](https://github.com/SpigotMC/BungeeCord/) using [BungeeTabListPlus](https://github.com/CodeCrafter47/BungeeTabListPlus), and even got the server owner to give me the server's config file for the tab list), but was unable to reproduce it (though still could on the real server).

The only relevant difference between the servers is that one is filled with real players, and the other is just me and a bunch of fake players to fill the tab menu to try and re-create it. I tried to get an account with an OF cape to appear in tab on my test server but I don't have access to an account that has one and the fake accounts use default skins :/ I did get one real player (with a fake account, in offline mode) with a cape in-game, but a default skin in-game and in tab and it didn't crash. Not sure whether that's helpful or not.

After far too long I narrowed it down to this mod. I'm not sure exactly what in the tab list is causing it, but something is. The hat layer on skins isn’t visible in the tab list anymore and used to before it was changed and made the mod crash, so maybe it’s something related to that? I don't know... Anyway, here's the crash (everything else in the log is not relevant):
```
[17:34:47] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1011.method_4307()" because "this.field_5200" is null
	at net.minecraft.class_1043.method_22793(class_1043.java:21) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:179) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1137) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
If you want more information I can try and provide it, though I'm somewhat limited in how much I can provide since said server is a semi-private whitelisted server, but I'll do my best if you ask. Thank you for your work on this mod. :)

;-; Forgot to mention this so here's an edit: I'm using 1.17.1 and v3.0.0 of Kappa (v3.0.1 doesn't work on 1.17.1, and the server where the crash happens hasn't been updated to 1.18.1 yet so I can't try that)

**Comment by hibiii** [comment]
Offline mode shouldn't matter when showing capes from players, it should only matter if you are trying to change the cape, which you aren't.

Generally, plugins that use player entities to show bots, statues, or NPCs use randomly generated usernames.
The chance of Kappa putting capes on any of them is very small because names such as `xLz0uYDZxYumDVKa` and `jEqGG7UlLTco1W6j` aren't particularly glamorous, most people wouldn't use them, and even then it would only happen if there was a real player with the exact username, and it wouldn't break, it would just be a bot with a cape.

Your stacktrace means a crash because an image is null and it's trying to render it, but it doesn't say where it is from or what uses it.
This shouldn't be possible, because at most the cape should be a completely new `NativeImage` without any content, and not null.
Could you try to reproduce the crash with [Fabric Capes](https://www.curseforge.com/minecraft/mc-mods/capes) or [OF Capes](https://www.curseforge.com/minecraft/mc-mods/of-capes)?
Also, could you try it with [Multiconnect](https://www.curseforge.com/minecraft/mc-mods/multiconnect) and the latest version of Kappa v3.0.1 on 1.18.1?

Also, Kappa doesn't mess with the tab list itself, or what skin parts players have enabled, you probably disabled Hat List if you have it installed. :P

Additionally, you could talk to the server admin and whitelist me so I can take a deeper look and check if some other possibility is happening, like either a cape being corrupted on OF's servers or a MiTM attack targetting OF like Mantle and Cloaks+.

I can't figure out what's causing the crash from your report alone.
If you'd like to DM, add me on Discord, my username is `hibi#0025`.

**Comment by Purrrpley** [comment]
It doesn't crash with [Fabric Capes](https://www.curseforge.com/minecraft/mc-mods/capes) or [OF Capes](https://www.curseforge.com/minecraft/mc-mods/of-capes), only with Kappa... Using Kappa v3.0.1 on 1.18.1 connecting using [Multiconnect](https://www.curseforge.com/minecraft/mc-mods/multiconnect) (which I forgot existed... Oops) does still crash.

I've done a lot more research on it this time (in particular trying to figure out a way to reproduce it without being on a specific server) and I think I know why it's happening now! :D I've been able to reproduce it on my test server, and fix the crash (though potentially not properly, see below for details). I'm not a Java developer (well not really anyway, I don't know much about it but I can guess what's going on and what stuff is doing due to knowledge from other languages), so this may be inaccurate, but based on the information gathered by adding some lines of code in specific places logging different things, I think this is what is happening:

* Opening the player list loads player skins from players in the list, and their capes (including OptiFine capes loaded by this mod). It's not what causes the crash, but it does mean that opening it can quickly make the mod try to load a lot of capes at once which combined with other things explained later creates a problem.
* When a player is loaded, this mod will try to download the OptiFine cape from OptiFine's servers (over a HTTP connection instead of a HTTPS connection, for some reason... I'll probably make a PR changing that later and you can merge it if you want).
* If the cape doesn't exist, the URL will return a HTTP 404 error and will be caught by the `try...catch` block and do nothing.
* If the cape does exist, it will do some cropping stuff (not exactly sure what that does or why it does it but it's not important here), creates an image, and registers the image as a dynamic texture with the ID of `minecraft:dynamic/kappa<player_name>_<id>`. The image can never be `null` when it's created.
* (This is even more so speculation than everything else here but I imagine it's mostly correct) the only way for an existing image to be `null` is if it's closed using the `NativeImageBackedTexture.close()` method, which is never called by this mod. It may be called by other things, though. When it's called it's likely called based on ID to close the correct texture once it's no longer needed, which shouldn't ever be a problem as long as each texture has its own ID. If two textures did have the same ID though, where one was still being used, and the other wasn't needed anymore and so was attempting to be closed, the attempt at closing the second one could end up closing the first one instead. Then the next time the first one tries to render it'll be trying to render a null texture, which crashes the client.
* When registering a dynamic texture, an `_<id>` is added to the end so if you try to register two textures with the same string they'll get different IDs... But for whatever reason this caps out at `79` and once it reaches that it can give numbers it's used before (seemingly not even starting back at 1, where it begins), which means you can get different textures with the same ID.
* For that to happen though (from this mod) you would need to have registered 80 cape textures to the same player name... Normally that would never happen, but on servers with lots of fake players to keep tab to an 80 player size (4 columns, 20 rows) where each fake player has the same name and a cape, this can happen.
* In the case of the server that I was playing on where I experiences this crash the first time, the names of the fake players were "" (an empty string) because of BungeeCord's config option `experimentalTabCompleteFixForTabSize80` being set to true. I didn't have this set on my test server, but after setting it there I was able to get my client to crash by viewing the tab list on my test server.
* The player name "" [actually has an OptiFine cape](https://optifine.net/capes/.png) for whatever reason, so if you load enough of them it can get close to 80 but not quite there... They do get reloaded sometimes though when the server wants to move players around in the tab list when someone joins or something, and so because of that can get to over 80 and then once one of them tries to close (likely when it disappears off the tab list which happens when players in it are moved around) the client will crash because there's now a null texture for whichever other fake player was also using the same texture ID.

I imagine there's probably some clever way to properly solve this by like checking if a cape has already been loaded and reusing the texture if so or something (caching), or fixing the `79` ID cap on dynamic textures (likely out of scope for a simple cape mod though). I'm not sure how to do that though so instead I just made the dynamic texture ID be generated based off of the UUID of the player instead of its name, which seem to be unique for players with the same empty string name generated by BungeeCord (and, really, should away be unique because it's a **Universally Unique** IDentifier).

I'm not sure why you made it use the player name to register the dynamic textures - [Fabric Capes](https://github.com/CaelTheColher/Capes/blob/master/src/main/kotlin/me/cael/capes/handler/PlayerHandler.kt#L125) and [OF Capes](https://github.com/dragonostic/of-capes/blob/main/src/main/java/net/drago/ofcapes/util/PlayerHandler.java#L57) both don't. Using UUIDs instead of player names fixes the crash, sort of. I think it might still possible to happen with UUIDs, but far rarer. I waited a while with the tab list open and logging the IDs of the dynamic cape textures created and saw the ending `_<id>` thing keep incrementing, It's much slower, though (took a few minutes to get up to 13 and then I decided I'd write this instead of waiting even more), and once it reaches the point where it starts reusing IDs the textures that were previously using the IDs are likely to have been closed already.

I'll likely make a PR changing it to use UUIDs soon (have to go to eat dinner now, I've spent a while on this...) and you can merge that if you want. It *might* not completely fix it, but it's a lot better than what's currently done (and even that took a while for it to go wrong and someone to make a bug report about it, so using UUIDs is probably fine).

**Comment by hibiii** [comment]
I got all of that, but some points of adamant:

- The player name `` is invalid. I don't care if OptiFine has a cape for it, I care if it's possible in game.
- OptiFine registers cape names by usernames and not UUIDs, therefore it's only sensible for me to use names for it.

That being said, an easy fix would be to check if `Provider.capes` has an `Identifier` for the player name that it's trying to load, right at the head of `loadCape:runnable`. This would however, bring the need of restarting the game if you want to see your cape change, instead of just relogging, which itself can be mitigated by clearing `Provider.capes` on a new connection. I think I'll do that but I'll also take a look at your PRs.

As for me using an HTTP request, `s.optifine.net` doesn't support HTTPS. `optifine.net` itself upgrades HTTP requests to HTTPS, but I can't check how the OptiFine mod does it because I don't have a copy of it with me and `optifine.net` is down, so I can't download an up-to-date version.
