### ISSUE TITLE
Kappa prioritizes Mojang capes over OptiFine capes

### ISSUE THREAD

**Issue by DBTDerpbox** [hibiii/Kappa#7]
If you have both an OptiFine and a cape from Mojang (migrator, minecon, etc..) it will prioritize the Mojang cape over OptiFine, only showing the OptiFine cape after disabling the Mojang one in the launcher skin settings

would it be possible to maybe add a config option to switch the priority to OptiFine?

**Comment by hibiii** [comment]
No, this is intended behavior. Kappa prioritizes official capes because they're official, and OptiFine capes shouldn't even exist if you go by the commercial usage guidelines.
